version: "3.8"
services:
  
  django: 
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/usr/src/backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: ./backend 
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    links:
      - redis
    volumes:
      - ./backend:/usr/src/backend
    depends_on:
      - django 
      - redis 

  db:
    image: postgres
    env_file:
      .env
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis: 
    image: redis:alpine


volumes:
  dbdata: 
