version: "3.8"
services:
  
  django: 
    build: ./backend
    command: >
      bash -c "python manage.py migrate --no-input
      && python manage.py collectstatic --no-input
      && gunicorn --config gunicorn_config.py config.wsgi:application"
    volumes:
      - ./backend:/backend
      - static:/backend/static
      - media:/backend/media
    expose:
      - 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build: ./backend 
    command: celery -A config worker --loglevel=info
    env_file:
      - .env
    links:
      - redis
    volumes:
      - ./backend:/backend
    depends_on:
      - django 
      - redis 

  db:
    image: postgres
    env_file:
      .env
    volumes:
      - dbdata:/var/lib/postgresql/data

  redis: 
    image: redis:alpine

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static:/static
      - media:/media
    depends_on:
      - django

volumes:
  dbdata: 
  static:
  media:
