# Generated by Django 5.0 on 2023-12-31 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.UniqueConstraint(fields=('owner', 'post'), name='unique_owner_post'),
        ),
    ]
